# -*- coding: utf-8 -*-
"""Project-2 [Research Paper] Part-1 NLP Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UGMDfSiuRfPiIzHmqZA85t1STC-mojuv

# **Install & Load Dataset**
"""

!pip install datasets

from datasets import load_dataset

dataset = load_dataset("CShorten/ML-ArXiv-Papers" , split = 'train')

print(dataset)

dataset[0]

"""# **DataFrame Creation**"""

import pandas as pd

df = pd.DataFrame(dataset)

df

df.columns

df = df[ ['title' , 'abstract'] ]

df.shape

df = df.head(15000)

df.shape

df.isnull().sum()

df["paper_text"] = df["title"] + " " + df["abstract"]

df["paper_text"].head()

df[["paper_text"]].head()

type(df["paper_text"].iloc[0])

"""# **SentenceTransformer**"""

from sentence_transformers import SentenceTransformer

model = SentenceTransformer("all-MiniLM-L6-v2")

print(type(model))

df["paper_text"] = df["paper_text"].str.replace("\n", " ",regex=False)

df["paper_text"] = df["paper_text"].str.strip()

"""# **Embedding [of 1]**"""

sample_text = df["paper_text"].iloc[0]

sample_text

embedding = model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

embedding[:56]

"""# **Embedding [of 5]**"""

sample_of_5_embedding = model.encode(df["paper_text"].head(5).to_list())

print(sample_of_5_embedding.shape)

sample_of_5_embedding

"""# **Cosine Similarity [of 5]**"""

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[0].reshape(1, -1))
print(similarity)

similarity = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1) , sample_of_5_embedding[1].reshape(1, -1))
print(similarity)

for i in range(0,5):
  sim  = cosine_similarity(sample_of_5_embedding[0].reshape(1, -1), sample_of_5_embedding[i].reshape(1, -1))
  print(sim)

"""# **FAISS [of 5]**"""

!pip install faiss-cpu

import faiss

faiss.normalize_L2(sample_of_5_embedding)

index = faiss.IndexFlatIP(384)

print(index.ntotal)

index.add(sample_of_5_embedding)

print(index.ntotal)

query = "deep learning for medical image analysis"

query_embedding = model.encode(query)
query_embedding.shape

query_embedding.reshape(1,-1)

query_embedding.shape

query_embedding = model.encode([query])
query_embedding.shape

faiss.normalize_L2(query_embedding)

D, I = index.search(query_embedding, 5)

print(D)
print(I)

"""# **Embedding [of all 15000]**"""

import os
import numpy as np

if os.path.exists("paper_embeddings.npy"):
    print("Loading saved embeddings...")
    embeddings = np.load("paper_embeddings.npy")

else:
    print("Generating embeddings...")
    embeddings = model.encode(df["paper_text"].to_list() , batch_size=32 , show_progress_bar=True)
    np.save("paper_embeddings.npy", embeddings)
    print("Embeddings saved successfully!")

print(embeddings.shape)
print(type(embeddings))
embeddings.dtype

"""# **FAISS [of 15000]**"""

if os.path.exists("paper_faiss.index"):
    print("Loading existing FAISS index...")
    index = faiss.read_index("paper_faiss.index")

else:
    print("Creating new FAISS index...")
    faiss.normalize_L2(embeddings)
    index = faiss.IndexFlatIP(384)
    index.add(embeddings)

    faiss.write_index(index, "paper_faiss.index")
    print("FAISS index saved successfully!")

print(index.ntotal)

query = "deep learning for medical image analysis"
query_embedding = model.encode([query])
query_embedding.shape
faiss.normalize_L2(query_embedding)
D, I = index.search(query_embedding, 5)
print(D) # Similarity Score
print(I) # Indices

df.iloc[10466]["title"]

df.iloc[10466]["abstract"]

df.iloc[11873]["title"]

df.iloc[11873]["abstract"]

"""# **Search [return]**"""

def search_paper_return(query, k=5):
  # Generate query embedding
  query_embedding = model.encode([query])

  # Normalize query embedding
  faiss.normalize_L2(query_embedding)

  # Search in FAISS index
  D, I = index.search(query_embedding, k)

  return D, I

D , I = search_paper_return("deep learning for medical image analysis")
print(D)
print(I)

"""# **Search [display - zip()]**"""

def search_paper_display(query, k = 5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0] , I[0]), start = 1):
      print()
      print("=" * 100)
      print()
      print(f"Result Rank        : #{rank}")

      print(f"Paper Index        : {idx}")

      print(f"Similarity Score   : {score:.4f}")

      print(f"\nTitle: {df.iloc[idx]['title']}")

      print(f"\nAbstract: {df.iloc[idx]['abstract'][:500]}")

search_paper_display("deep learning for medical image analysis")

"""# **Summarize [BART]**"""

!pip install transformers==4.46.3

from transformers import pipeline

summarizer = pipeline("summarization" , model = "facebook/bart-large-cnn")

type(summarizer)

summary = summarizer(df.iloc[10466]["abstract"] , max_length = 120  ,min_length = 40)

print(summary)

type(summary)

type(summary[0])

summary[0]["summary_text"]

"""# **Search + Summarize**"""

def search_and_summarize(query, k=5):

  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)

  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]) , start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print(f"\nTitle:")
    print(df.iloc[idx]["title"])

    print(f"\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    # Generate summary
    summary = summarizer(df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)

    print("\nSummary:")
    print(summary[0]["summary_text"])
    print("\n")

search_and_summarize("Deep learning in medical imaging" , k = 5)

"""# **Keyword**"""

!pip install keybert

from keybert import KeyBERT

kw_model = KeyBERT(model)

type(kw_model) # model = SentenceTransformer("all-MiniLM-L6-v2")

text = df.iloc[10466]["abstract"]
keywords = kw_model.extract_keywords(text)

print(keywords)

print(type(keywords))

print(type(keywords[0]))

keywords = kw_model.extract_keywords(text , keyphrase_ngram_range = (1, 3) , stop_words = "english")

print(keywords)

"""# **Search + Summarize + Keyword**"""

def search_summarize_keywords(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)

  for rank, (score, idx) in enumerate(zip(D[0], I[0]), start = 1):
    print()
    print("=" * 100)
    print()

    print(f"Result Rank        : #{rank}")
    print(f"Paper Index        : {idx}")
    print(f"Similarity Score   : {score:.4f}")

    print("\nTitle:")
    print(df.iloc[idx]["title"])

    print("\nAbstract Preview:")
    print(df.iloc[idx]["abstract"][:500])

    print()

    # Generate summary
    summary = summarizer( df.iloc[idx]["abstract"] , max_length = 120, min_length = 40, do_sample = False)
    print("Summary:")
    print(summary[0]["summary_text"])
    print()

    # Extract keywords from the abstract
    keywords = kw_model.extract_keywords( df.iloc[idx]["abstract"] , keyphrase_ngram_range = (1, 3), stop_words = "english")

    print("Keywords:")

    for keyword, score in keywords:
      print(keyword)
    print("\n")

search_summarize_keywords("natural language processing using transformers", k = 5)

"""# **Here NLP concludes!!!**
   


"""